name: Code Coverage Report
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: anuraag016/Jest-Coverage-Diff@master
      with:
        fullCoverageDiff: false
        runCommand: "npx jest --collectCoverageFrom='[\"src/**/*.{js,jsx,ts,tsx}\"]' --coverage --collectCoverage=true --coverageDirectory='./' --coverageReporters='json-summary' --forceExit --detectOpenHandles test/.*test.*"
        delta: 0.5
