on: pull_request

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm i

      - name: Comment with Test Coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
