on: pull_request

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Comment with Test Coverage
        uses: raulanatol/jest-coverage-comment-action@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          jest-command: npm run test --coverage
