name: Code Coverage Report
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: ./coverage/lcov.info
