name: Code Coverage Report
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: anuraag016/Jest-Coverage-Diff@master
      with:
        fullCoverageDiff: false
        runCommand: "npm run test --collectCoverageFrom='[\"src/**/*.{ts,tsx}\"]' --coverage --collectCoverage=true --coverageDirectory='./coverage' --coverageReporters='json-summary'"
        delta: 0.5
