name: 'coverage'
on: pull_request
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - uses: ziishaned/jest-reporter-action@v0.0.1
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                test-command: "npm run test --coverage"
